<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Active_flexSwitchCheckChecked</name>
   <tag></tag>
   <elementGuidId>bb2d63f7-3c4f-4a88-9ecb-c6a4cbfa52bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='flexSwitchCheckChecked'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b6c1a70-6b2c-4a5e-9b1b-5f821b42133c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>c23a7e4b-bd1b-4941-9161-0f8c9c2af647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1e24e54a-75b6-4fc5-904d-f239324b236e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>00bf3b9c-636b-4f98-be98-dd0aecf9d2a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flexSwitchCheckChecked</value>
      <webElementGuid>1b5091cd-f754-4548-b50a-9ebe62d4c36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>changeStatus(19, 1, this)</value>
      <webElementGuid>7788e90e-dc3e-4489-8097-334693af1978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl_report&quot;)/tr[5]/td[5]/div[@class=&quot;form-check form-switch&quot;]/input[@id=&quot;flexSwitchCheckChecked&quot;]</value>
      <webElementGuid>f5d74d82-07b4-4a39-af0d-b9e96e3d4c89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='flexSwitchCheckChecked'])[5]</value>
      <webElementGuid>bf3f3718-3aa3-4dda-b039-db43766b09ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tbl_report']/tr[5]/td[5]/div/input</value>
      <webElementGuid>ff26b915-4cf5-4777-b43f-4078f53017b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[5]/div/input</value>
      <webElementGuid>c77d11a5-d6c9-4217-8f1b-e8d2cb9202dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'flexSwitchCheckChecked']</value>
      <webElementGuid>d4c4304a-4614-4810-bd0f-b5ef9eda4f0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
