<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Inactive_flexSwitchCheckChecked</name>
   <tag></tag>
   <elementGuidId>6eee305a-7512-4aa3-91df-39bfd266e728</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='flexSwitchCheckChecked'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c5a30670-15f7-4487-b5ab-00a0dbf8dfc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>444fba9d-228d-4b12-81db-10dfcf0d93a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2982a67b-b7ad-4cc4-b887-cb2c391e5883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>5ce04106-306f-4388-a2b3-176c6e175084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flexSwitchCheckChecked</value>
      <webElementGuid>79d40e88-b89d-48db-850b-1f30a4506ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>changeStatus(19, 0, this)</value>
      <webElementGuid>585f213f-ffcb-4da5-a250-c87506ed7a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl_report&quot;)/tr[5]/td[5]/div[@class=&quot;form-check form-switch&quot;]/input[@id=&quot;flexSwitchCheckChecked&quot;]</value>
      <webElementGuid>43cf9856-368b-40f1-85b8-1b43dd5bf242</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='flexSwitchCheckChecked'])[5]</value>
      <webElementGuid>026e11ab-2f81-4ad8-8f33-db66bb17efd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tbl_report']/tr[5]/td[5]/div/input</value>
      <webElementGuid>3b2bc1eb-7c1f-4691-b46f-5fc099900ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[5]/div/input</value>
      <webElementGuid>f15080ad-6ffb-4dd1-8299-737c961d8816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'flexSwitchCheckChecked']</value>
      <webElementGuid>05ec9a80-93d9-424b-9acd-015cd5305707</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
