<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_descriptionApprove</name>
   <tag></tag>
   <elementGuidId>6273f6ca-9a80-433a-8934-cfe5abb19a85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='descriptionApprove']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#descriptionApprove</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d508952-a016-4cc1-8a59-61d3d245d48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6df01279-c03d-44eb-b02d-a3b1e50fc99d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>309b776e-baaf-48fa-a75a-2903b1b6cbf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>descriptionApprove</value>
      <webElementGuid>9217e1ff-e9bd-4418-a0a6-3fcfcef560bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;descriptionApprove&quot;)</value>
      <webElementGuid>efb9c67b-ef26-4b61-843c-2b5e9e449900</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='descriptionApprove']</value>
      <webElementGuid>2a65b537-d65d-4d53-b343-2a2a8cf5d57b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='approveModal']/div/div/div[2]/form/div/input</value>
      <webElementGuid>53a86d44-6204-47e4-b475-b475303d075d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>0ab20f64-b2ef-45ad-846c-4aea78c11d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'descriptionApprove']</value>
      <webElementGuid>6d171207-d965-44f5-9409-20603c7b0c8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
