<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_approver - Testing_rounded-circle</name>
   <tag></tag>
   <elementGuidId>223f6716-fc62-4fd0-a0ce-52136c087693</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rounded-circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='user-image']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0a790b95-d6cf-43bc-a04f-8160fec7b5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://10.202.200.141/assets/images/users/avatar-1.jpg</value>
      <webElementGuid>c9ecdf29-8a5b-4839-9dc8-b007799aae8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>user-image</value>
      <webElementGuid>d95ba0f1-da79-4fff-9039-297e48e69d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>be554795-4e2d-47ba-bae4-daee2de663fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-circle</value>
      <webElementGuid>aaafaeb3-b1e9-4805-95c2-25b034c28cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;menuitem-active&quot;]/body[@class=&quot;show&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;navbar-custom&quot;]/div[@class=&quot;topbar container-fluid&quot;]/ul[@class=&quot;topbar-menu d-flex align-items-center gap-3&quot;]/li[@class=&quot;dropdown&quot;]/a[@class=&quot;nav-link dropdown-toggle arrow-none nav-user show&quot;]/span[@class=&quot;account-user-avatar&quot;]/img[@class=&quot;rounded-circle&quot;]</value>
      <webElementGuid>4b2951a1-15f4-436b-a7e7-ee055b1eaef2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='user-image']</value>
      <webElementGuid>63a0752a-07eb-452f-96f6-74b31efffc87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/span/img</value>
      <webElementGuid>a4e58ea1-ed8b-4c6f-9591-f61878b79ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://10.202.200.141/assets/images/users/avatar-1.jpg' and @alt = 'user-image']</value>
      <webElementGuid>acadd3d0-d6c7-41e0-bda6-e3db4ea65475</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
