<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_failed change password_oldPassword</name>
   <tag></tag>
   <elementGuidId>e7edb1d5-b2e9-448b-b1c1-849b7b4fe4de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#oldPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='oldPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82dcefc5-3959-4fbd-b36f-4d35b85e99e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fdfed471-c874-41a6-b21e-b2202cf2f51d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oldPassword</value>
      <webElementGuid>bbf6c788-d02b-4065-bc57-b66fe74847ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Old Password</value>
      <webElementGuid>cad6b9bf-9eef-4db7-8c88-6f7e430a5eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c54333da-d5cd-4e96-83e2-92ca172be3f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oldPassword&quot;)</value>
      <webElementGuid>b074d5d8-2bea-4c89-93e6-00c8ccc0fd27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='oldPassword']</value>
      <webElementGuid>ea0cf13c-32e5-44e2-ade5-1ce9fcfa2127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b060d2fa-b397-4639-8bda-8c42a9c632d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'oldPassword' and @placeholder = 'Old Password' and @type = 'password']</value>
      <webElementGuid>fa663823-edf9-4688-bc65-52ff841e8b51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
