<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No Rekening Tujuan_noRekeningTujuan</name>
   <tag></tag>
   <elementGuidId>099c1b39-3893-465b-9264-b798720008d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#noRekeningTujuan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='noRekeningTujuan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2084b4f-9060-4875-8cd8-134d4659cf93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a04bb624-0b6c-440e-9c75-f472eead6eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6cbfbda3-908e-4533-8f38-b156e7deb1cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>noRekeningTujuan</value>
      <webElementGuid>15f993fb-0be6-41b1-8897-f821868a6c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Insert No Rekening Tujuan</value>
      <webElementGuid>d05a74d4-db6e-43ca-bc48-6403446d8622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noRekeningTujuan&quot;)</value>
      <webElementGuid>0ae3afeb-b10f-4098-967c-c88469f0383a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='noRekeningTujuan']</value>
      <webElementGuid>4a7ab231-8ca4-4ff7-b42c-0f9718ee371a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='transactionForm']/div[2]/input</value>
      <webElementGuid>31912a44-815c-4ab9-a1bc-51d946528dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>9a69f1bf-5e56-4457-9d65-ae2374254676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'noRekeningTujuan' and @placeholder = 'Insert No Rekening Tujuan']</value>
      <webElementGuid>580dedcb-0656-4661-b3db-5ba92a48c563</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
