<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Issuer ID_issuerId</name>
   <tag></tag>
   <elementGuidId>b31ec8a7-bb92-4dab-88da-92afc14342e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#issuerId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='issuerId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27e5b878-8f2d-43a7-8f04-d7ec1a2cc6f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>73074e98-4b10-49b3-97f9-f7966b77f23a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4f9ab424-d8ff-4c33-b974-9492714e0f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>issuerId</value>
      <webElementGuid>e7c9cceb-b450-4928-9c08-83bb9066bd8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Insert issuer ID</value>
      <webElementGuid>c273da7f-8ab1-4e9b-a973-05bb2f18ca37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;issuerId&quot;)</value>
      <webElementGuid>f1df0c89-7071-46c3-96c5-bd9520a1bdc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='issuerId']</value>
      <webElementGuid>a414f996-90e8-43db-a57e-21f08aad85d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='transactionForm']/div/input</value>
      <webElementGuid>23e7bce9-20d7-4203-a654-6c06ca9be5b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>cd097194-5740-4fba-85fd-261ecad3c876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'issuerId' and @placeholder = 'Insert issuer ID']</value>
      <webElementGuid>75f87043-3723-466e-8855-0e9004bad247</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
