<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__confirmPassword</name>
   <tag></tag>
   <elementGuidId>9b824cf9-7d35-46b8-a2b3-65baa5154edd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirmPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirmPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29cbdc2d-eb35-424f-a137-f9a8f7ce47ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c1a92be0-d7f0-4001-be20-8fb77d874cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmPassword</value>
      <webElementGuid>47c3ab85-e673-43dc-87d6-58c8bc4ce362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm Password</value>
      <webElementGuid>0c02cecf-ceb9-4afc-9331-90b4d6bbf249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e4acf43a-3caa-4424-8c03-51c5862bc7c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmPassword&quot;)</value>
      <webElementGuid>aefee7d0-3805-4634-aef6-7cf75aeeade3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirmPassword']</value>
      <webElementGuid>54aec02c-9536-4ecb-996b-43f080e299ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>c9021acc-cc33-4ad3-9f45-8d414863d7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'confirmPassword' and @placeholder = 'Confirm Password' and @type = 'password']</value>
      <webElementGuid>5991eb48-5c8c-44c7-b997-63bd27eb8478</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
