<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Reject</name>
   <tag></tag>
   <elementGuidId>be031062-60ef-4bf1-a355-1c8382f1e0a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='showRejectModal(67)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-xs.btn-outline-danger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>46a4ef15-ff60-4f86-9eb4-a301bc0391c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-xs btn-outline-danger</value>
      <webElementGuid>fd866096-02b9-4089-993c-e03716389f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showRejectModal(67)</value>
      <webElementGuid>f24478b1-03f1-4717-9b1c-44d6eb312686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reject</value>
      <webElementGuid>e2f2719c-db43-4b21-b6ba-ba7da593431c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl_report&quot;)/tr[@class=&quot;text-center&quot;]/td[9]/button[@class=&quot;btn btn-xs btn-outline-danger&quot;]</value>
      <webElementGuid>f5b46d17-53e0-434a-8c03-cd8691c320cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='showRejectModal(67)']</value>
      <webElementGuid>c1dccf35-9a4d-4c67-8c69-c5d73451b2fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tbl_report']/tr/td[9]/button[2]</value>
      <webElementGuid>f695af2c-07c9-4303-96cb-90c9e8b5e57e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approve'])[1]/following::button[1]</value>
      <webElementGuid>ce815ccf-d633-479c-9525-5f4bb78f8fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pending'])[1]/following::button[2]</value>
      <webElementGuid>acb5f589-7561-46c0-8d16-3d40ae909e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ahmd'])[2]/preceding::button[1]</value>
      <webElementGuid>164060e3-ad33-4f66-8da5-2bf87b815007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[2]/preceding::button[1]</value>
      <webElementGuid>c731c548-151e-46e5-b47c-a0ae8cf9b585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reject']/parent::*</value>
      <webElementGuid>461e962e-a1dc-404c-bf77-107eff0f748c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/button[2]</value>
      <webElementGuid>d2fe3f10-0685-4643-9d81-eb938fa66056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Reject' or . = 'Reject')]</value>
      <webElementGuid>d9c4cb05-fe56-43e1-8b43-9e3c378db41d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='showRejectModal(66)']</value>
      <webElementGuid>55b70b2d-e159-4417-9bd3-2daae0a99fb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
