<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No Rekening Tujuan_noRekeningTujuan</name>
   <tag></tag>
   <elementGuidId>dcb653c1-5ae3-42a7-9c12-7d2ecc18787f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#noRekeningTujuan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='noRekeningTujuan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a6bf69c-12e8-443f-9d80-e16b7b71388c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c586917b-08ba-4825-a342-4b3543fddc51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cd3d62ee-c573-46eb-b80a-48bdd3aa04c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>noRekeningTujuan</value>
      <webElementGuid>fdbe7918-b224-4607-bad3-ff6d55216088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Insert No Rekening Tujuan</value>
      <webElementGuid>be4b0723-cc06-4916-bdf8-203e6dff2226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noRekeningTujuan&quot;)</value>
      <webElementGuid>396e7a0d-c3d1-40c9-8e0b-7c9f7545efe5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='noRekeningTujuan']</value>
      <webElementGuid>8c81a16a-d44d-4c1f-beec-82669a1e69f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='transactionForm']/div[2]/input</value>
      <webElementGuid>a3f054f8-33e8-40f0-aab1-27c500b06e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>00c6ac07-3b25-4370-96f4-6c947b344572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'noRekeningTujuan' and @placeholder = 'Insert No Rekening Tujuan']</value>
      <webElementGuid>ad963dee-f6f6-42bb-8467-bf92e07f7501</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
