<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Issuer ID_issuerId</name>
   <tag></tag>
   <elementGuidId>e1ebd8a4-dfe2-41c6-85bd-21ddfdae5b1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#issuerId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='issuerId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b7be86d-cec7-479e-ab83-d95db7ecaa25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>31cbdae8-3423-4f9a-8811-53787a96bff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>39219c0e-3126-4adf-98db-383f97ad3e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>issuerId</value>
      <webElementGuid>4f51b50a-4f41-49d3-be24-ed2454b8bfa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Insert issuer ID</value>
      <webElementGuid>8d8a838f-6e5f-462b-8f4f-7782e3d16fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;issuerId&quot;)</value>
      <webElementGuid>34332488-de18-4e0b-aee1-fbcd98a8bef3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='issuerId']</value>
      <webElementGuid>52f104d2-9155-4d6d-9f19-3701efc2025c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='transactionForm']/div/input</value>
      <webElementGuid>e621e9a3-631a-4245-beee-84eaf4ac6350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a59df4cb-445b-4301-a3ce-b873e79c3cae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'issuerId' and @placeholder = 'Insert issuer ID']</value>
      <webElementGuid>8cb151de-74f4-42df-bc0b-65aad69177d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
