<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Issuer ID_issuerId</name>
   <tag></tag>
   <elementGuidId>4a600978-d643-4e7c-a518-914f60c37f3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#issuerId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='issuerId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6972b113-e5d0-4a4d-b52c-2e3f0d507117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c6eeab7c-c30c-4c58-8c7a-df4ebe4d9648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7e8e802e-8630-4958-85c9-bc81872b6493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>issuerId</value>
      <webElementGuid>4ca0d00c-6ae5-40df-a29d-cccfac203119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Insert issuer ID</value>
      <webElementGuid>941b5328-262b-4c17-97df-b3340f23c545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;issuerId&quot;)</value>
      <webElementGuid>7d0ff8b2-22e6-4964-9df3-1c101ae47c96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='issuerId']</value>
      <webElementGuid>bbee100c-a655-4974-8931-5403e1c885ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='transactionForm']/div/input</value>
      <webElementGuid>1597c663-b9b3-44d9-96c2-2515d9bf263b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6b63fbe7-4284-4a04-908a-af78ff282f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'issuerId' and @placeholder = 'Insert issuer ID']</value>
      <webElementGuid>953484ed-37ac-4d88-9a35-77654884c0bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
