<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No Rekening Tujuan_noRekeningTujuan</name>
   <tag></tag>
   <elementGuidId>d0d762e4-4015-4156-914d-69075b092480</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#noRekeningTujuan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='noRekeningTujuan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95f7692b-dab7-48a0-9788-d1e0f670d2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f476e65a-c931-456c-8a23-bf5b6da9165d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>be66ab79-d9da-4573-a829-491acc1bfbe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>noRekeningTujuan</value>
      <webElementGuid>fc21beb9-627b-4e1b-9515-d7827f12893a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Insert No Rekening Tujuan</value>
      <webElementGuid>619d94c6-aad3-4772-a552-b059c8b8c4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noRekeningTujuan&quot;)</value>
      <webElementGuid>fd8726e0-a489-456b-b094-2810e8fa007c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='noRekeningTujuan']</value>
      <webElementGuid>5fc65536-8cba-4492-8ed3-90f112605e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='transactionForm']/div[2]/input</value>
      <webElementGuid>da2b2519-1ef5-488b-8251-af2b2ca449ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>97067148-58fd-4f02-a161-ff94034b499f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'noRekeningTujuan' and @placeholder = 'Insert No Rekening Tujuan']</value>
      <webElementGuid>a858c58e-9016-4b45-80c1-592310717589</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
