<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Keterangan_keterangan</name>
   <tag></tag>
   <elementGuidId>67701111-e223-47d5-8b66-a02f7e79dc7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#keterangan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='keterangan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>039ced73-090f-467a-bd38-8e391223df9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>47e0052f-07fc-47c7-b20a-125d2dfdd406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keterangan</value>
      <webElementGuid>3a2361b6-e5e2-4d94-88a7-9ba84bd38310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>8d2cfdf0-025a-41c6-9377-c7434d03277d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Insert keterangan</value>
      <webElementGuid>7e349f17-ca40-439d-8a80-47c2a4639e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keterangan&quot;)</value>
      <webElementGuid>297c6edd-717e-44a1-ab71-0c7897d704ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='keterangan']</value>
      <webElementGuid>c0f1a4d3-c01b-4e63-b8a8-3ed228af7337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='transactionForm']/div[4]/textarea</value>
      <webElementGuid>d426cbff-51e6-4f7c-97fa-5a63ec66cc4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>29c8462d-ae5c-4d62-85a8-c6d9269cadb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'keterangan' and @placeholder = 'Insert keterangan']</value>
      <webElementGuid>1a310503-042e-4cff-b621-a4948ec485d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
