<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_descriptionApprove</name>
   <tag></tag>
   <elementGuidId>ba65727e-cefc-4c36-9c3f-54fdfe417bf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#descriptionApprove</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='descriptionApprove']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d92be73d-cb70-459e-a35b-2cd23c4f1e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>076d1cd4-8c6b-4cf1-b198-7fff632a703d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f75fa555-0eb3-4efd-afd2-32283bb8d598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>descriptionApprove</value>
      <webElementGuid>5e4cebcb-735c-4148-8a24-2efa777c0562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;descriptionApprove&quot;)</value>
      <webElementGuid>d52b51aa-f5cd-435c-bcb9-d9f9c2e8a966</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='descriptionApprove']</value>
      <webElementGuid>70128591-997a-45fa-98ff-71a7dc1c24cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='approveModal']/div/div/div[2]/form/div/input</value>
      <webElementGuid>2aa1fd38-a44a-46a9-b17e-5112d193964b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>25009310-61a4-4507-9a03-0013318733ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'descriptionApprove']</value>
      <webElementGuid>1fcac732-7b9d-430a-8444-f9b5f84c6903</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
